### ISSUE TITLE
Compose Navigation

### ISSUE THREAD

**Issue by armond1978** [atick-faisal/Jetpack-Compose-Starter#92]
Is there still any plan to migrate to Compose Navigation?

I noticed that the following issue has been closed a few months ago, but I don't see any implementation in the code base:
https://github.com/atick-faisal/Jetpack-Compose-Starter/issues/16

Thanks.

**Comment by atick-faisal** [comment]
Hi! I considered migrating to compose navigation in the past. But compared to fragment navigation, it felt like a downgrade. I personally do not like how the compose navigation is implemented (Hence the issue was closed). That being said, moving forward, I will migrate this to compose navigation soon. I use this template heavily for all my projects and do not want to carry legacy navigation code. Thanks for checking out. I will close this issue once I implement the compose navigation.

**Comment by armond1978** [comment]
@atick-faisal Thanks for your response and thanks for considering the migration. Just as a reference, you might want to take a look at the following project, and that how the navigation has been implemented there:
https://github.com/android/nowinandroid

**Comment by armond1978** [comment]
By the way, is there any ETA for the migration?

**Comment by atick-faisal** [comment]
Hi! I have been following the NowInAndroid project closely and I copied and modified several things from it into this project. I look forward to using it for the navigation setup too. Thanks for sharing though. Right now I don't have a fixed eta for it. I hope to do it within the following week.

**Comment by atick-faisal** [comment]
Hi, @armond1978. Compose navigation is now available. Feel free to check it out.
